server:
  port: 8082

spring:
  application:
    name: project-service

# 日志配置
logging:
  level:
    com.codivio.project: INFO

# Actuator 监控
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always