# Docker环境配置
spring:
  # 数据源配置 - Docker环境
  datasource:
    url: jdbc:mysql://mysql:3306/codivio_user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: codivio
    password: codivio123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # Docker环境连接池优化
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1200000

# 日志配置 - Docker环境
logging:
  level:
    com.codivio.userservice: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: ERROR