server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # 用户服务路由 (本地测试配置)
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**
        # 项目服务路由 (本地测试配置)
        - id: project-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/projects/**
        # 协作服务路由 (预留)
        - id: collaboration-service
          uri: http://collaboration-service:8083
          predicates:
            - Path=/api/v1/collaboration/**
        # 文件服务路由 (预留)
        - id: file-service
          uri: http://file-service:8084
          predicates:
            - Path=/api/v1/files/**

# 日志配置
logging:
  level:
    com.codivio.gateway: INFO
    org.springframework.cloud.gateway: DEBUG

# JWT配置
jwt:
  secret: codivio-jwt-secret-key-2025-very-long-and-secure-string
  expiration: 86400
  issuer: codivio-user-service

# Actuator 监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# 服务地址配置
services:
  user-service:
    url: http://localhost:8081