server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # 用户服务路由
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/user/**
        # 项目服务路由 (预留)
        - id: project-service
          uri: http://project-service:8082
          predicates:
            - Path=/api/project/**
        # 协作服务路由 (预留)
        - id: collaboration-service
          uri: http://collaboration-service:8083
          predicates:
            - Path=/api/collaboration/**
        # 文件服务路由 (预留)
        - id: file-service
          uri: http://file-service:8084
          predicates:
            - Path=/api/file/**

# 日志配置
logging:
  level:
    com.codivio.gateway: INFO
    org.springframework.cloud.gateway: DEBUG

# Actuator 监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always