server:
  port: 8084

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# 日志配置
logging:
  level:
    com.codivio.file: INFO

# Actuator 监控
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always