services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: codivio-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: codivio_dev
      MYSQL_PASSWORD: codivio123
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./database/mysql/init:/docker-entrypoint-initdb.d
    command: >
      --default-authentication-plugin=mysql_native_password 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4;'
      --innodb-flush-log-at-trx-commit=0
    networks:
      - codivio-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: codivio-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes --requirepass redis123
    networks:
      - codivio-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 20s
      retries: 10

  # MongoDB文档数据库
  mongodb:
    image: mongo:6.0
    container_name: codivio-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: codivio_logs_dev
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - codivio-dev-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 20s
      retries: 10

  # phpMyAdmin (可选，方便数据库管理)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: codivio-phpmyadmin-dev
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: codivio_dev
      PMA_PASSWORD: codivio123
      # 设置字符集
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - codivio-dev-network
    volumes:
      - ./database/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  mysql_dev_data:
  redis_dev_data:
  mongodb_dev_data:

networks:
  codivio-dev-network:
    driver: bridge
